#
# what the heck...
#
branches:
  only:
  - master
dist: trusty
language: cpp
install:
  - sudo apt-get install -qq -y docker
  - pip install --user cpp-coveralls
matrix:
  fast_finish: true
  include:
  - compiler: gcc
    os: linux
    script: ./test.sh gcc
services:
- docker
sudo: required
