#
# what the heck...
#
branches:
  only:
  - master
dist: trusty
language: cpp
matrix:
  fast_finish: true
  include:
  - compiler: gcc
    env:
    install: sudo apt-get install -qq -y docker; docker pull ubuntu:16.10
    os: linux
    script: docker images; docker run -it --rm --name hessian_x3 ubuntu:16.10; sleep 10; docker exec hessian_x3 gcc --version
services:
- docker
sudo: required
