#
# what the heck...
#
branches:
  only:
  - master
dist: trusty
language: cpp
matrix:
  fast_finish: true
  include:
  - compiler: gcc
    env:
    install: sudo apt-get install -qq -y docker
    os: linux
    script: docker images
services:
- docker
sudo: required
